target:
  language: python
  path: examples/json_validator.py
  input_type: json
  trigger_to_generate_input: "Generate a JSON string for API validation"
  input_hint: "{\"user\": \"admin\"}"
fuzzing:
  type: generation
  language: json
  max_iterations: 100
  batch_size: 10
  output_folder: outputs/json_validator/
  otf: true
  log_level: 3
  prompt_strategy: 2
llm:
  model_name: bigcode/starcoderbase
  device: gpu
  batch_size: 10
  temperature: 1
  max_length: 1024
